apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql2
  labels:
    app: things-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: things-server
  template:
    metadata:
      labels:
        app: things-server
    spec:
      containers:
      - name: things-server
        image: betterptdev/things-server:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: graphql2
spec:
  selector:
    app: things-server
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000