apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  labels:
    app: balls-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: balls-server
  template:
    metadata:
      labels:
        app: balls-server
    spec:
      containers:
      - name: balls-server
        image: betterptdev/balls-server:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: graphql
spec:
  selector:
    app: balls-server
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000